language: node_js
node_js: v4.5.0

install:
  - npm run install

script:
  - npm run configure
  - npm run build
  - npm run test

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8